// Licence file C:\Users\Максим\Documents\ReversePOCO.txt not found.
// Please obtain your licence file at www.ReversePOCO.co.uk, and place it in your documents folder shown above.
// Defaulting to Trial version.
// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace zv_practica
{
    #region Database context interface

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface IMyDbContext : IDisposable
    {
        DbSet<Адрес> Адрес { get; set; } // Адрес
        DbSet<Заказ> Заказ { get; set; } // Заказ
        DbSet<Заказтовара> Заказтовара { get; set; } // Заказ_товара
        DbSet<Категории> Категории { get; set; } // Категории
        DbSet<Оценкатовара> Оценкатовара { get; set; } // Оценка_товара
        DbSet<Пользователи> Пользователи { get; set; } // Пользователи
        DbSet<Товар> Товар { get; set; } // Товар

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);
    }

    #endregion

    #region Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class MyDbContext : DbContext, IMyDbContext
    {
        public MyDbContext()
        {
        }

        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }

        public DbSet<Адрес> Адрес { get; set; } // Адрес
        public DbSet<Заказ> Заказ { get; set; } // Заказ
        public DbSet<Заказтовара> Заказтовара { get; set; } // Заказ_товара
        public DbSet<Категории> Категории { get; set; } // Категории
        public DbSet<Оценкатовара> Оценкатовара { get; set; } // Оценка_товара
        public DbSet<Пользователи> Пользователи { get; set; } // Пользователи
        public DbSet<Товар> Товар { get; set; } // Товар

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=(local);Initial Catalog=магазин;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new АдресConfiguration());
            modelBuilder.ApplyConfiguration(new ЗаказConfiguration());
            modelBuilder.ApplyConfiguration(new ЗаказтовараConfiguration());
            modelBuilder.ApplyConfiguration(new КатегорииConfiguration());
            modelBuilder.ApplyConfiguration(new ОценкатовараConfiguration());
            modelBuilder.ApplyConfiguration(new ПользователиConfiguration());
            modelBuilder.ApplyConfiguration(new ТоварConfiguration());
        }

    }

    #endregion

    #region Database context factory

    public class MyDbContextFactory : IDesignTimeDbContextFactory<MyDbContext>
    {
        public MyDbContext CreateDbContext(string[] args)
        {
            return new MyDbContext();
        }
    }

    #endregion

    #region Fake Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class FakeMyDbContext : IMyDbContext
    {
        public DbSet<Адрес> Адрес { get; set; } // Адрес
        public DbSet<Заказ> Заказ { get; set; } // Заказ
        public DbSet<Заказтовара> Заказтовара { get; set; } // Заказ_товара
        public DbSet<Категории> Категории { get; set; } // Категории
        public DbSet<Оценкатовара> Оценкатовара { get; set; } // Оценка_товара
        public DbSet<Пользователи> Пользователи { get; set; } // Пользователи
        public DbSet<Товар> Товар { get; set; } // Товар

        public FakeMyDbContext()
        {
            _database = new FakeDatabaseFacade(new MyDbContext());

            Адрес = new FakeDbSet<Адрес>("Login");
            Заказ = new FakeDbSet<Заказ>("OrderNumber");
            Заказтовара = new FakeDbSet<Заказтовара>("OrderNumber", "ProductId");
            Категории = new FakeDbSet<Категории>("CategoryId");
            Оценкатовара = new FakeDbSet<Оценкатовара>("ProductId", "Login");
            Пользователи = new FakeDbSet<Пользователи>("Login");
            Товар = new FakeDbSet<Товар>("ProductId");

        }

        public int SaveChangesCount { get; private set; }
        public virtual int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public virtual int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            return SaveChanges();
        }

        public virtual Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }
        public virtual Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(x => 1, acceptAllChangesOnSuccess, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private DatabaseFacade _database;
        public DatabaseFacade Database { get { return _database; } }

        public DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Add(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual Task AddRangeAsync(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual async Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual void AddRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AddRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Attach(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Entry(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual TEntity Find<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual object Find(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Remove(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Update(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression)
        {
            throw new NotImplementedException();
        }

    }

    #endregion

    #region Fake DbSet

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    public class FakeDbSet<TEntity> :
        DbSet<TEntity>,
        IQueryable<TEntity>,
        IAsyncEnumerable<TEntity>,
        IListSource,
        IResettableService
        where TEntity : class
    {
        private readonly PropertyInfo[] _primaryKeys;
        private ObservableCollection<TEntity> _data;
        private IQueryable _query;
        public override IEntityType EntityType { get; }

        public FakeDbSet()
        {
            _primaryKeys = null;
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override ValueTask<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken));
        }

        public override ValueTask<TEntity> FindAsync(params object[] keyValues)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues)));
        }

        public override EntityEntry<TEntity> Add(TEntity entity)
        {
            _data.Add(entity);
            return null;
        }

        public override ValueTask<EntityEntry<TEntity>> AddAsync(TEntity entity, CancellationToken cancellationToken = default)
        {
            return new ValueTask<EntityEntry<TEntity>>(Task<EntityEntry<TEntity>>.Factory.StartNew(() => Add(entity), cancellationToken));
        }

        public override void AddRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override void AddRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override Task AddRangeAsync(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities));
        }

        public override Task AddRangeAsync(IEnumerable<TEntity> entities, CancellationToken cancellationToken = default)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities), cancellationToken);
        }

        public override EntityEntry<TEntity> Attach(TEntity entity)
        {
            if (entity == null) throw new ArgumentNullException("entity");
            return Add(entity);
        }

        public override void AttachRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override void AttachRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override EntityEntry<TEntity> Remove(TEntity entity)
        {
            _data.Remove(entity);
            return null;
        }

        public override void RemoveRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities.ToList())
                _data.Remove(entity);
        }

        public override void RemoveRange(IEnumerable<TEntity> entities)
        {
            RemoveRange(entities.ToArray());
        }

        public override EntityEntry<TEntity> Update(TEntity entity)
        {
            _data.Remove(entity);
            _data.Add(entity);
            return null;
        }

        public override void UpdateRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            RemoveRange(entities);
            AddRange(entities);
        }

        public override void UpdateRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var array = entities.ToArray();        RemoveRange(array);
            AddRange(array);
        }

        bool IListSource.ContainsListCollection => true;

        public IList GetList()
        {
            return _data;
        }

        IList IListSource.GetList()
        {
            return _data;
        }

        Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_data); }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        IEnumerator<TEntity> IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        public override IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }

        public void ResetState()
        {
            _data  = new ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public Task ResetStateAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.Factory.StartNew(() => ResetState());
        }
    }

    public class FakeDbAsyncQueryProvider<TEntity> : FakeQueryProvider<TEntity>, IAsyncEnumerable<TEntity>, IAsyncQueryProvider
    {
        public FakeDbAsyncQueryProvider(Expression expression) : base(expression)
        {
        }

        public FakeDbAsyncQueryProvider(IEnumerable<TEntity> enumerable) : base(enumerable)
        {
        }

        public TResult ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
        {
            var expectedResultType = typeof(TResult).GetGenericArguments()[0];
            var executionResult = typeof(IQueryProvider)
                .GetMethods()
                .First(method => method.Name == nameof(IQueryProvider.Execute) && method.IsGenericMethod)
                .MakeGenericMethod(expectedResultType)
                .Invoke(this, new object[] { expression });

            return (TResult) typeof(Task).GetMethod(nameof(Task.FromResult))
                ?.MakeGenericMethod(expectedResultType)
                .Invoke(null, new[] { executionResult });
        }

        public IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }
    }

    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, IAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(IEnumerable<T> enumerable)
            : base(enumerable)
        {
        }

        public FakeDbAsyncEnumerable(Expression expression)
            : base(expression)
        {
        }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = new CancellationToken())
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        IAsyncEnumerator<T> IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
        {
            return GetAsyncEnumerator(cancellationToken);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.AsEnumerable().GetEnumerator();
        }
    }

    public class FakeDbAsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private readonly IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        public ValueTask<bool> MoveNextAsync()
        {
            return new ValueTask<bool>(_inner.MoveNext());
        }

        public ValueTask DisposeAsync()
        {
            _inner.Dispose();
            return new ValueTask(Task.CompletedTask);
        }
    }

    public abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider
    {
        private IEnumerable<T> _enumerable;

        protected FakeQueryProvider(Expression expression)
        {
            Expression = expression;
        }

        protected FakeQueryProvider(IEnumerable<T> enumerable)
        {
            _enumerable = enumerable;
            Expression = enumerable.AsQueryable().Expression;
        }

        public IQueryable CreateQuery(Expression expression)
        {
            if (expression is MethodCallExpression m)
            {
                var resultType = m.Method.ReturnType; // it should be IQueryable<T>
                var tElement = resultType.GetGenericArguments().First();
                return (IQueryable) CreateInstance(tElement, expression);
            }

            return CreateQuery<T>(expression);
        }

        public IQueryable<TEntity> CreateQuery<TEntity>(Expression expression)
        {
            return (IQueryable<TEntity>) CreateInstance(typeof(TEntity), expression);
        }

        private object CreateInstance(Type tElement, Expression expression)
        {
            var queryType = GetType().GetGenericTypeDefinition().MakeGenericType(tElement);
            return Activator.CreateInstance(queryType, expression);
        }

        public object Execute(Expression expression)
        {
            return CompileExpressionItem<object>(expression);
        }

        public TResult Execute<TResult>(Expression expression)
        {
            return CompileExpressionItem<TResult>(expression);
        }

        IEnumerator<T> IEnumerable<T>.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        public Type ElementType => typeof(T);

        public Expression Expression { get; }

        public IQueryProvider Provider => this;

        private static TResult CompileExpressionItem<TResult>(Expression expression)
        {
            var visitor = new FakeExpressionVisitor();
            var body = visitor.Visit(expression);
            var f = Expression.Lambda<Func<TResult>>(body ?? throw new InvalidOperationException(string.Format("{0} is null", nameof(body))), (IEnumerable<ParameterExpression>) null);
            return f.Compile()();
        }
    }

    public class FakeExpressionVisitor : ExpressionVisitor
    {
    }

    public class FakeDatabaseFacade : DatabaseFacade
    {
        public FakeDatabaseFacade(DbContext context) : base(context)
        {
        }

        public override bool EnsureCreated()
        {
            return true;
        }

        public override Task<bool> EnsureCreatedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureCreated());
        }

        public override bool EnsureDeleted()
        {
            return true;
        }

        public override Task<bool> EnsureDeletedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureDeleted());
        }

        public override bool CanConnect()
        {
            return true;
        }

        public override Task<bool> CanConnectAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(CanConnect());
        }

        public override IDbContextTransaction BeginTransaction()
        {
            return new FakeDbContextTransaction();
        }

        public override Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(BeginTransaction());
        }

        public override void CommitTransaction()
        {
        }

        public override Task CommitTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override void RollbackTransaction()
        {
        }

        public override Task RollbackTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override IExecutionStrategy CreateExecutionStrategy()
        {
            return null;
        }

        public override string ToString()
        {
            return string.Empty;
        }
    }

    public class FakeDbContextTransaction : IDbContextTransaction
    {
        public Guid TransactionId => Guid.NewGuid();
        public void Commit() { }
        public void Rollback() { }
        public Task CommitAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public Task RollbackAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public void Dispose() { }
        public ValueTask DisposeAsync() => default;
    }

    #endregion

    #region POCO classes

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Адрес
    public class Адрес
    {
        public string City { get; set; } // City (length: 50)
        public string Country { get; set; } // Country (length: 50)
        public string Street { get; set; } // Street (length: 50)
        public string House { get; set; } // House (length: 50)
        public string Appartments { get; set; } // Appartments (length: 50)
        public string Login { get; set; } // Login (Primary key) (length: 50)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Адрес pointed by [Пользователи].[Login] (FK_Пользователи_Адрес)
        /// </summary>
        public Пользователи Пользователи { get; set; } // Пользователи.FK_Пользователи_Адрес
    }

    // Заказ
    public class Заказ
    {
        public int OrderNumber { get; set; } // Order_number (Primary key)
        public DateTime? OrderDate { get; set; } // Order_date
        public string Login { get; set; } // Login (length: 50)
        public double? Price { get; set; } // Price
        public bool IsDeleted { get; set; } // IsDeleted
        public string DeliveryType { get; set; } // Delivery_Type (length: 50)
        public string Status { get; set; } // Status (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Заказтовара where [Заказ_товара].[Order_number] point to this entity (FK_Заказ_товара_Заказ)
        /// </summary>
        public ICollection<Заказтовара> Заказтовара { get; set; } // Заказ_товара.FK_Заказ_товара_Заказ

        // Foreign keys

        /// <summary>
        /// Parent Пользователи pointed by [Заказ].([Login]) (FK_Заказ_Пользователи)
        /// </summary>
        public Пользователи Пользователи { get; set; } // FK_Заказ_Пользователи

        public Заказ()
        {
            Заказтовара = new List<Заказтовара>();
        }
    }

    // Заказ_товара
    public class Заказтовара
    {
        public int OrderNumber { get; set; } // Order_number (Primary key)
        public int ProductId { get; set; } // Product_ID (Primary key)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Заказ pointed by [Заказ_товара].([OrderNumber]) (FK_Заказ_товара_Заказ)
        /// </summary>
        public Заказ Заказ { get; set; } // FK_Заказ_товара_Заказ

        /// <summary>
        /// Parent Товар pointed by [Заказ_товара].([ProductId]) (FK_Заказ_товара_Товар)
        /// </summary>
        public Товар Товар { get; set; } // FK_Заказ_товара_Товар
    }

    // Категории
    public class Категории
    {
        public string CategoryName { get; set; } // Category_name (length: 50)
        public string Comments { get; set; } // Comments (length: 50)
        public int CategoryId { get; set; } // Category_ID (Primary key)
        public bool? IsDeleted { get; set; } // Is_Deleted

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Категории pointed by [Товар].[Product_ID] (FK_Товар_Категории)
        /// </summary>
        public Товар Товар { get; set; } // Товар.FK_Товар_Категории
    }

    // Оценка_товара
    public class Оценкатовара
    {
        public int ProductId { get; set; } // Product_ID (Primary key)
        public string Login { get; set; } // Login (Primary key) (length: 50)
        public int? Grade { get; set; } // Grade
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Пользователи pointed by [Оценка_товара].([Login]) (FK_Оценка_товара_Пользователи)
        /// </summary>
        public Пользователи Пользователи { get; set; } // FK_Оценка_товара_Пользователи

        /// <summary>
        /// Parent Товар pointed by [Оценка_товара].([ProductId]) (FK_Оценка_товара_Товар)
        /// </summary>
        public Товар Товар { get; set; } // FK_Оценка_товара_Товар
    }

    // Пользователи
    public class Пользователи
    {
        public string Login { get; set; } // Login (Primary key) (length: 50)
        public string Password { get; set; } // Password (length: 50)
        public string Surname { get; set; } // Surname (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public string Lastname { get; set; } // Lastname (length: 50)
        public DateTime Birthday { get; set; } // Birthday
        public bool IsDeleted { get; set; } // IsDeleted
        public bool IsAdmin { get; set; } // IsAdmin

        // Reverse navigation

        /// <summary>
        /// Child Заказ where [Заказ].[Login] point to this entity (FK_Заказ_Пользователи)
        /// </summary>
        public ICollection<Заказ> Заказ { get; set; } // Заказ.FK_Заказ_Пользователи

        /// <summary>
        /// Child Оценкатовара where [Оценка_товара].[Login] point to this entity (FK_Оценка_товара_Пользователи)
        /// </summary>
        public ICollection<Оценкатовара> Оценкатовара { get; set; } // Оценка_товара.FK_Оценка_товара_Пользователи

        // Foreign keys

        /// <summary>
        /// Parent Адрес pointed by [Пользователи].([Login]) (FK_Пользователи_Адрес)
        /// </summary>
        public Адрес Адрес { get; set; } // FK_Пользователи_Адрес

        public Пользователи()
        {
            Заказ = new List<Заказ>();
            Оценкатовара = new List<Оценкатовара>();
        }
    }

    // Товар
    public class Товар
    {
        public int ProductId { get; set; } // Product_ID (Primary key)
        public double? ProductPrice { get; set; } // Product_Price
        public double? ProductWeight { get; set; } // Product_weight
        public double? ProductLenght { get; set; } // Product_Lenght
        public double? ProductWidth { get; set; } // Product_width
        public string Comment { get; set; } // Comment (length: 100)
        public bool IsDeleted { get; set; } // IsDeleted
        public int? SumProduct { get; set; } // Sum_product

        // Reverse navigation

        /// <summary>
        /// Child Заказтовара where [Заказ_товара].[Product_ID] point to this entity (FK_Заказ_товара_Товар)
        /// </summary>
        public ICollection<Заказтовара> Заказтовара { get; set; } // Заказ_товара.FK_Заказ_товара_Товар

        /// <summary>
        /// Child Оценкатовара where [Оценка_товара].[Product_ID] point to this entity (FK_Оценка_товара_Товар)
        /// </summary>
        public ICollection<Оценкатовара> Оценкатовара { get; set; } // Оценка_товара.FK_Оценка_товара_Товар

        // Foreign keys

        /// <summary>
        /// Parent Категории pointed by [Товар].([ProductId]) (FK_Товар_Категории)
        /// </summary>
        public Категории Категории { get; set; } // FK_Товар_Категории

        public Товар()
        {
            Заказтовара = new List<Заказтовара>();
            Оценкатовара = new List<Оценкатовара>();
        }
    }


    #endregion

    #region POCO Configuration

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Адрес
    public class АдресConfiguration : IEntityTypeConfiguration<Адрес>
    {
        public void Configure(EntityTypeBuilder<Адрес> builder)
        {
            builder.ToTable("Адрес", "dbo");
            builder.HasKey(x => x.Login).HasName("PK_Адрес").IsClustered();

            builder.Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Country).HasColumnName(@"Country").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Street).HasColumnName(@"Street").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.House).HasColumnName(@"House").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Appartments).HasColumnName(@"Appartments").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Login).HasColumnName(@"Login").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50).ValueGeneratedNever();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
        }
    }

    // Заказ
    public class ЗаказConfiguration : IEntityTypeConfiguration<Заказ>
    {
        public void Configure(EntityTypeBuilder<Заказ> builder)
        {
            builder.ToTable("Заказ", "dbo");
            builder.HasKey(x => x.OrderNumber).HasName("PK_Заказ").IsClustered();

            builder.Property(x => x.OrderNumber).HasColumnName(@"Order_number").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.OrderDate).HasColumnName(@"Order_date").HasColumnType("date").IsRequired(false);
            builder.Property(x => x.Login).HasColumnName(@"Login").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Price).HasColumnName(@"Price").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.DeliveryType).HasColumnName(@"Delivery_Type").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Status).HasColumnName(@"Status").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.Пользователи).WithMany(b => b.Заказ).HasForeignKey(c => c.Login).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Заказ_Пользователи");
        }
    }

    // Заказ_товара
    public class ЗаказтовараConfiguration : IEntityTypeConfiguration<Заказтовара>
    {
        public void Configure(EntityTypeBuilder<Заказтовара> builder)
        {
            builder.ToTable("Заказ_товара", "dbo");
            builder.HasKey(x => new { x.OrderNumber, x.ProductId }).HasName("PK_Заказ_товара").IsClustered();

            builder.Property(x => x.OrderNumber).HasColumnName(@"Order_number").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProductId).HasColumnName(@"Product_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Заказ).WithMany(b => b.Заказтовара).HasForeignKey(c => c.OrderNumber).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Заказ_товара_Заказ");
            builder.HasOne(a => a.Товар).WithMany(b => b.Заказтовара).HasForeignKey(c => c.ProductId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Заказ_товара_Товар");
        }
    }

    // Категории
    public class КатегорииConfiguration : IEntityTypeConfiguration<Категории>
    {
        public void Configure(EntityTypeBuilder<Категории> builder)
        {
            builder.ToTable("Категории", "dbo");
            builder.HasKey(x => x.CategoryId).HasName("PK_Категории").IsClustered();

            builder.Property(x => x.CategoryName).HasColumnName(@"Category_name").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Comments).HasColumnName(@"Comments").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.CategoryId).HasColumnName(@"Category_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsDeleted).HasColumnName(@"Is_Deleted").HasColumnType("bit").IsRequired(false);
        }
    }

    // Оценка_товара
    public class ОценкатовараConfiguration : IEntityTypeConfiguration<Оценкатовара>
    {
        public void Configure(EntityTypeBuilder<Оценкатовара> builder)
        {
            builder.ToTable("Оценка_товара", "dbo");
            builder.HasKey(x => new { x.ProductId, x.Login }).HasName("PK_Оценка_товара").IsClustered();

            builder.Property(x => x.ProductId).HasColumnName(@"Product_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Login).HasColumnName(@"Login").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50).ValueGeneratedNever();
            builder.Property(x => x.Grade).HasColumnName(@"Grade").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Пользователи).WithMany(b => b.Оценкатовара).HasForeignKey(c => c.Login).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Оценка_товара_Пользователи");
            builder.HasOne(a => a.Товар).WithMany(b => b.Оценкатовара).HasForeignKey(c => c.ProductId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Оценка_товара_Товар");
        }
    }

    // Пользователи
    public class ПользователиConfiguration : IEntityTypeConfiguration<Пользователи>
    {
        public void Configure(EntityTypeBuilder<Пользователи> builder)
        {
            builder.ToTable("Пользователи", "dbo");
            builder.HasKey(x => x.Login).HasName("PK_Пользователи").IsClustered();

            builder.Property(x => x.Login).HasColumnName(@"Login").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50).ValueGeneratedNever();
            builder.Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Surname).HasColumnName(@"Surname").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Lastname).HasColumnName(@"Lastname").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType("date").IsRequired();
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsAdmin).HasColumnName(@"IsAdmin").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Адрес).WithOne(b => b.Пользователи).HasForeignKey<Пользователи>(c => c.Login).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Пользователи_Адрес");
        }
    }

    // Товар
    public class ТоварConfiguration : IEntityTypeConfiguration<Товар>
    {
        public void Configure(EntityTypeBuilder<Товар> builder)
        {
            builder.ToTable("Товар", "dbo");
            builder.HasKey(x => x.ProductId).HasName("PK_Товар").IsClustered();

            builder.Property(x => x.ProductId).HasColumnName(@"Product_ID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProductPrice).HasColumnName(@"Product_Price").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.ProductWeight).HasColumnName(@"Product_weight").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.ProductLenght).HasColumnName(@"Product_Lenght").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.ProductWidth).HasColumnName(@"Product_width").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.Comment).HasColumnName(@"Comment").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.SumProduct).HasColumnName(@"Sum_product").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Категории).WithOne(b => b.Товар).HasForeignKey<Товар>(c => c.ProductId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Товар_Категории");
        }
    }


    #endregion

}
// </auto-generated>
